export type UnderworldProPackEntry = {
  id: string;
  building: string;
  level: number;
  gold: number | null;
  shrooms: number | null;
  souls: number | null;
  baseTimeMinutes: number | null;
};

export const UNDERWORLD_PRO_PACK_ENTRIES: UnderworldProPackEntry[] = [
  {
    id: "heart-of-darkness-1",
    building: "Heart of Darkness",
    level: 1,
    gold: null,
    shrooms: 2,
    souls: null,
    baseTimeMinutes: 31,
  },
  {
    id: "soul-extractor-1",
    building: "Soul Extractor",
    level: 1,
    gold: 250,
    shrooms: 2,
    souls: null,
    baseTimeMinutes: 66,
  },
  {
    id: "gladiator-trainer-1",
    building: "Gladiator Trainer",
    level: 1,
    gold: 700,
    shrooms: 2,
    souls: 148,
    baseTimeMinutes: 140,
  },
  {
    id: "heart-of-darkness-2",
    building: "Heart of Darkness",
    level: 2,
    gold: 2000,
    shrooms: 4,
    souls: 616,
    baseTimeMinutes: 300,
  },
  {
    id: "soul-extractor-2",
    building: "Soul Extractor",
    level: 2,
    gold: 500,
    shrooms: 4,
    souls: 462,
    baseTimeMinutes: 480,
  },
  {
    id: "gladiator-trainer-2",
    building: "Gladiator Trainer",
    level: 2,
    gold: 1400,
    shrooms: 4,
    souls: 554,
    baseTimeMinutes: 685,
  },
  {
    id: "heart-of-darkness-3",
    building: "Heart of Darkness",
    level: 3,
    gold: 3000,
    shrooms: 7,
    souls: 1650,
    baseTimeMinutes: 1107,
  },
  {
    id: "soul-extractor-3",
    building: "Soul Extractor",
    level: 3,
    gold: 750,
    shrooms: 7,
    souls: 1235,
    baseTimeMinutes: 2400,
  },
  {
    id: "gladiator-trainer-3",
    building: "Gladiator Trainer",
    level: 3,
    gold: 2100,
    shrooms: 7,
    souls: 1485,
    baseTimeMinutes: 5236,
  },
  {
    id: "heart-of-darkness-4",
    building: "Heart of Darkness",
    level: 4,
    gold: 4000,
    shrooms: 14,
    souls: 4220,
    baseTimeMinutes: 11446,
  },
  {
    id: "soul-extractor-4",
    building: "Soul Extractor",
    level: 4,
    gold: 1000,
    shrooms: 14,
    souls: 3165,
    baseTimeMinutes: 19200,
  },
  {
    id: "gladiator-trainer-4",
    building: "Gladiator Trainer",
    level: 4,
    gold: 2800,
    shrooms: 14,
    souls: 3800,
    baseTimeMinutes: 28800,
  },
  {
    id: "heart-of-darkness-5",
    building: "Heart of Darkness",
    level: 5,
    gold: 5000,
    shrooms: 30,
    souls: 11000,
    baseTimeMinutes: 36933,
  },
  {
    id: "soul-extractor-5",
    building: "Soul Extractor",
    level: 5,
    gold: 1250,
    shrooms: 30,
    souls: 8250,
    baseTimeMinutes: 48000,
  },
  {
    id: "gladiator-trainer-5",
    building: "Gladiator Trainer",
    level: 5,
    gold: 3500,
    shrooms: 30,
    souls: 9900,
    baseTimeMinutes: null,
  },
  {
    id: "heart-of-darkness-6",
    building: "Heart of Darkness",
    level: 6,
    gold: 6000,
    shrooms: 48,
    souls: 25080,
    baseTimeMinutes: null,
  },
  {
    id: "soul-extractor-6",
    building: "Soul Extractor",
    level: 6,
    gold: 1500,
    shrooms: 48,
    souls: 18810,
    baseTimeMinutes: null,
  },
  {
    id: "underworld-gate-1",
    building: "Underworld Gate",
    level: 1,
    gold: 500,
    shrooms: 2,
    souls: null,
    baseTimeMinutes: null,
  },
  {
    id: "underworld-gate-2",
    building: "Underworld Gate",
    level: 2,
    gold: 1000,
    shrooms: 4,
    souls: 55,
    baseTimeMinutes: null,
  },
  {
    id: "underworld-gate-3",
    building: "Underworld Gate",
    level: 3,
    gold: 1500,
    shrooms: 7,
    souls: 149,
    baseTimeMinutes: null,
  },
  {
    id: "underworld-gate-4",
    building: "Underworld Gate",
    level: 4,
    gold: 2000,
    shrooms: 14,
    souls: 380,
    baseTimeMinutes: null,
  },
  {
    id: "underworld-gate-5",
    building: "Underworld Gate",
    level: 5,
    gold: 2500,
    shrooms: 30,
    souls: 990,
    baseTimeMinutes: null,
  },
  {
    id: "adventuromatic-1",
    building: "Adventuromatic",
    level: 1,
    gold: 10000,
    shrooms: 2,
    souls: 297,
    baseTimeMinutes: null,
  },
  {
    id: "keeper-1",
    building: "Keeper",
    level: 1,
    gold: 1500,
    shrooms: 2,
    souls: 198,
    baseTimeMinutes: null,
  },
  {
    id: "keeper-2",
    building: "Keeper",
    level: 2,
    gold: 3000,
    shrooms: 4,
    souls: 739,
    baseTimeMinutes: null,
  },
  {
    id: "keeper-3",
    building: "Keeper",
    level: 3,
    gold: 4500,
    shrooms: 7,
    souls: 1980,
    baseTimeMinutes: null,
  },
];

export const PRO_PACK_RESOURCES = {
  shrooms: 750,
  souls: 100000,
};
