import { admin } from "../firebase";

type FeatureStatus = "hidden" | "dev_only" | "beta" | "logged_in" | "public" | "active";
type Role = "guest" | "user" | "moderator" | "developer" | "admin";

type FeatureAccessSeed = {
  id: string;
  route: string;
  area: string;
  titleKey: string;
  status: FeatureStatus;
  minRole: Role;
  allowedRoles: Role[];
  allowedGroups: string[];
  allowedUserIds: string[];
  showInTopbar: boolean;
  showInSidebar: boolean;
  navOrder: number;
  isExperimental: boolean;
  description: string;
  createdAt: admin.firestore.FieldValue;
  updatedAt: admin.firestore.FieldValue;
};

type AccessGroupSeed = {
  id: string;
  label: string;
  description: string;
  userIds: string[];
  minRole: Role;
  allowedRoles: Role[];
  isSystem: boolean;
  createdAt: admin.firestore.FieldValue;
  updatedAt: admin.firestore.FieldValue;
};

const serverTimestamp = admin.firestore.FieldValue.serverTimestamp();

export const featureAccessSeeds: FeatureAccessSeed[] = [
  {
    id: "controlPanelAccessFeatures",
    route: "/access",
    area: "controlPanel",
    titleKey: "nav.controlPanel.access",
    status: "logged_in",
    minRole: "admin",
    allowedRoles: ["admin"],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 60,
    isExperimental: false,
    description: "Access control configuration page for the control panel.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.home",
    route: "/",
    area: "main",
    titleKey: "nav.home",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 5,
    isExperimental: false,
    description: "Home landing page for the main app.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.dashboard",
    route: "/dashboard",
    area: "main",
    titleKey: "nav.dashboard",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 10,
    isExperimental: false,
    description: "User dashboard overview.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.guildHub",
    route: "/guild-hub",
    area: "main",
    titleKey: "nav.guildHub",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 20,
    isExperimental: false,
    description: "Guild Hub overview and planner.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.discover",
    route: "/discover",
    area: "main",
    titleKey: "nav.discover",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 30,
    isExperimental: false,
    description: "Discover section with search and discovery tools.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.toplists",
    route: "/toplists",
    area: "main",
    titleKey: "nav.toplists",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 40,
    isExperimental: false,
    description: "Toplists across players, guilds and servers.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.guidehub",
    route: "/guidehub",
    area: "main",
    titleKey: "nav.guideHub",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 50,
    isExperimental: false,
    description: "Guide Hub with guides and calculators.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.tools",
    route: "/tools",
    area: "main",
    titleKey: "nav.tools",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 55,
    isExperimental: false,
    description: "Tools section with utilities.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.community",
    route: "/community",
    area: "main",
    titleKey: "nav.community",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 60,
    isExperimental: false,
    description: "Community news, records and scans.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.scans",
    route: "/scans",
    area: "main",
    titleKey: "nav.scans",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 70,
    isExperimental: false,
    description: "Scan overview and archive.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.settings",
    route: "/settings",
    area: "main",
    titleKey: "nav.settings",
    status: "active",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 80,
    isExperimental: false,
    description: "User settings and preferences.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.admin",
    route: "/admin",
    area: "main",
    titleKey: "nav.admin",
    status: "active",
    minRole: "moderator",
    allowedRoles: ["moderator", "admin"],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 90,
    isExperimental: false,
    description: "Administration pages for moderators and admins.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.playground",
    route: "/playground",
    area: "main",
    titleKey: "nav.playground",
    status: "beta",
    minRole: "developer",
    allowedRoles: ["developer", "admin"],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: true,
    navOrder: 100,
    isExperimental: true,
    description: "Playground and experimental demos.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "main.uploadCenter",
    route: "/upload-center",
    area: "main",
    titleKey: "feature.uploadCenter",
    status: "logged_in",
    minRole: "user",
    allowedRoles: [],
    allowedGroups: [],
    allowedUserIds: [],
    showInTopbar: false,
    showInSidebar: false,
    navOrder: 200,
    isExperimental: false,
    description: "Upload Center for importing player and guild scans into SFDataHub.",
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
];

export const accessGroupSeeds: AccessGroupSeed[] = [
  {
    id: "beta_testers",
    label: "Beta Testers",
    description: "Users who get access to beta features before public release.",
    userIds: [],
    minRole: "user",
    allowedRoles: ["user", "moderator", "developer", "admin"],
    isSystem: true,
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "dev_team",
    label: "Developer Team",
    description: "Internal developers who can access dev-only tools and debug views.",
    userIds: [],
    minRole: "developer",
    allowedRoles: ["developer", "admin"],
    isSystem: true,
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
  {
    id: "creator_program",
    label: "Creator Program",
    description: "Content creators with extra tools and stats.",
    userIds: [],
    minRole: "user",
    allowedRoles: ["user", "moderator", "developer", "admin"],
    isSystem: false,
    createdAt: serverTimestamp,
    updatedAt: serverTimestamp,
  },
];
